name: "Netease signin"

on:
  push:
    branches:
      - develop
  schedule:
    - cron: "31,40,50 1 * * 1-5"
    - cron: "*/10 2,5,6 * * 1-5"
    - cron: "0,10,20,31 3 * * 1-5"
    - cron: "31 7 * * 1-5"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup system timezone
        run: export TZ='Asia/Shanghai'
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - name: "Checkout codes"
        uses: actions/checkout@v2
      - name: "Set python 3.8"
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: "Install dependencies"
        run: python -m pip install --upgrade pandas requests
      - name: "Update smw data"
        env:
          SCAN_URL: ${{ secrets.SCAN_URL }}
          SCAN_PARAM: ${{ secrets.SCAN_PARAM }}
        run: python scan_smw.py
      - name: "Update long data"
        env:
          SCAN_URL: ${{ secrets.SCAN_URL_LONG }}
          SCAN_PARAM: ${{ secrets.SCAN_PARAM_LONG }}
        run: python scan_bb_long.py
      - name: "Commit"
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git add .
          git commit -m "update data" -a
      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TK }}
          force: true
