name: "SMA200"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "31 7 * * 1-5"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup timezone
        run: export TZ='Asia/Shanghai'
      # - name: Setup timezone
      #   uses: zcong1993/setup-timezone@master
      #   with:
      #     timezone: Asia/Shanghai
      # - name: "Setup python 3.x"
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.9.0"
      # - name: "Update pip3"
      #   run: /opt/hostedtoolcache/Python/3.9.0/x64/bin/python -m pip install --upgrade pip
      - name: "Install dependencies"
        run: python -m pip install pandas requests
      - name: "Checkout codes"
        uses: actions/checkout@v2
      - name: "Update SMA200"
        env:
          SCAN_URL: ${{ secrets.SCAN_URL }}
          SCAN_SMA200_PARAM: ${{ secrets.SCAN_SMA200_PARAM }}
        run: python scripts/scan_sma200.py
      - name: "Commit"
        run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git add .
          git commit -m "update data" -a
      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TK }}
          force: true
